spring.application.name=bookstore-batch

## Configuration for connecting to PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bookstore_pwd}

## To control how Hibernate automatically manages the database structure (schema) when the application starts
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

## Enable batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

## FTP
## Use FTP_HOST if the environment variable exists; otherwise use localhost
ftp.host=${FTP_HOST:localhost}
ftp.port=${FTP_PORT:21}
ftp.username=${FTP_USERNAME:bookstore}
ftp.password=${FTP_PASSWORD:bookstore123}
ftp.remote-directory=/incoming

## Batch
batch.local-directory=./imports