spring.application.name=bookstore-batch

## Configuration for connecting to PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

## To control how Hibernate automatically manages the database structure (schema) when the application starts
spring.jpa.hibernate.ddl-auto=update

## Enable SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

## Enable batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

## ftp
ftp.host=localhost
ftp.port=21
ftp.username=${}